#ifndef _GLOBAL_CONSTANTS_H
#define _GLOBAL_CONSTANTS_H

#define LOWER_TO_UPPER 32
#define START_UPPERCASE_ASCII 65

enum TABLE_RANGE{TABLE_MIN = 1, TABLE_MAX = 16};
enum ASCII_DIGIT_RANGE{MIN_DIGIT = 48, MAX_DIGIT = 57};

#endif